import os
os.system("pip install cowsay")
os.system("pip install rich")
os.system("pip install translate")
os.system("pip install requests")
os.system("pip install pyttsx3")
os.system("pip install qrcode")
os.system("pip install wikipedia")
os.system("pip install colorama")
os.system("pip install pytube")
os.system("pip install sounddevice")
os.system("pip install soundfile")
os.system("pip install numpy")
os.system("pip install vidstream")
os.system("pip install pyautogui")